### ISSUE TITLE
Let's discuss!

### ISSUE THREAD

**Issue by theo-armour** [Art/Art.github.io#2]
@Art 

GitHub issues is a great way of discussing things.

The benefits include that you can tag things and that you can close messages so you don't see them anymore after their task is finished. And there's much more.

But the main thing is that it's a great place to have a public discussion. A place where people way after the fact can come in and see how people arrived at a decision.

And I say this, because I think it's very important if you're working on free open-source software to have all the decision-making process be open as well. There's no need for back room discussions here.

Everybody can and should be able to listen in.

This does mean that they are two forums. The first is the Google Group which is for friends and people who should be kept informed of our work. The second form is here in the GitHub issues and that is for development work, technical aspects and all the things that it takes to make this project work.

There are a number of interesting aspects about the issues pages. The first thing is that a lot can be done by email. The second thing is that a special running format called  Markdown is supported which allows you to have links and other things very easily. And you can go back and edit your posts at any time. But enough for now, I can help you learn all the other bits as time goes on.

What do you think?

**Comment by theo-armour** [comment]
@Art 

Also note that it's usual to add people's names if you want them to comment. Also note that every message can have an emoji link to it. And this is good practice just to add one to indicate that you have read the message.

**Comment by Art** [comment]
@theo-armour It's all good
