### ISSUE TITLE
Mailing List

### ISSUE THREAD

**Issue by theo-armour** [Art/Art.github.io#3]
@Art 

There is now a discussion tag of 'mailing list' in GitHub issues.

Why? Because we need to do quite a few things in relationship to the mailing list.

The first thing is that we need 2 or 3 sentences as a template that can be included in invitations to join the mailing list. The second thing is that we need to start adding members once we have this invitation template.

Here is some first thoughts:

Welcome to the art-github-io@googlegroups.com mailing list.

This email list is for friends of the http://art.github.io web site

The mission of the project is to help youngsters and odlsters investigate aspects of science, technology, engineering and mathematics all with an emphasis on art.

**

Once we have a template we agreed then we can start sending it to peeps to add people to the mailing list.

It's just the first thoughts off the top of my head. Feel free to edit or completely change.

**Comment by Art** [comment]
Ok go I like it simple and straightforward clear

**Comment by theo-armour** [comment]
@Art 

Message added here:

https://groups.google.com/forum/#!groupsettings/art-github-io/information

Will be used in all welcome messages
